name: Octopus Clients PR Comment Check

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      # This is bypassed by the clients-pr-comment-bypass.yaml workflow. It will automatically set a success status for non-clients PRs.
      - 'clients/**'

jobs:
  validate-pr-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check Comments
        id: get_and_validate_comments
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            const commentBodies = comments.map(comment => comment.body);


            // ----------------------------
            // Get & Validate "release notes:"
            // ----------------------------

            // Check all the comments for any comment that contains the string "release notes:"
            // get list of comments that contain the string "release notes:"
            const releaseNotesComments = commentBodies.filter(comment => comment.toLowerCase().includes('release notes:'));

            // If there is one or multiple,
            if (releaseNotesComments.length === 0) {
              core.setFailed('"release notes:" comment is missing');
              core.setOutput('release_notes_error', '"release notes:" comment is missing');
            } else {
              // Validate the content of the release notes comment
              // - Check if the comment has content (Another action will extract release notes, we just need at least one thats valid.)
              const hasValidContent = releaseNotesComments.some(comment => {
                const content = comment.toLowerCase().split('release notes:')[1]?.trim();
                return content && content.length > 0;
              });
              if (!hasValidContent) {
                core.setFailed('"release notes:" comment found but no content');
                core.setOutput('release_notes_error', '"release notes:" comment found but no content');
              }
            }

            // ----------------------------
            // Get & Validate "semver:"
            // ----------------------------

            const allowedSemverValues = ["breaking", "feature", "no breaking changes", "major", "minor", "patch"];

            // Check all the comments for any comment that contains the string "semver:"
            // get list of comments that contain the string "semver:"
            const semverComments = commentBodies.filter(comment => comment.toLowerCase().includes('semver:'));
            if (semverComments.length === 0) {
              core.setOutput('semver_error', '"semver:" comment is missing');
              core.setFailed('"semver:" comment is missing');
            } else {  
              // Validate the content of the semver comment
              // - check value following semver: is an allowed semver value.
              const semverMatch = semverComments[0].toLowerCase().match(/semver:\s*(.+)/);
              const semverValue = semverMatch ? semverMatch[1].trim() : null;
              console.log(`Semver value found: "${semverValue}"`);
              console.log(`Allowed values: ${allowedSemverValues.join(', ')}`);

              if (!semverValue || !allowedSemverValues.includes(semverValue)) {
                core.setOutput('semver_error', `"semver:" comment found but invalid value: "${semverValue}". Allowed: ${allowedSemverValues.join(', ')}`);
                core.setFailed(`"semver:" comment found but invalid value: "${semverValue}". Allowed: ${allowedSemverValues.join(', ')}`);
              }
            }

      - name: Set success status
        id: set_success_status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            // using the potential `core.setFailed` of the previous steps update the create commit status to reflect success or failure from previous steps. combining the failed failures
            const validateCommentsFailed = '${{ steps.get_and_validate_comments.outcome }}' === 'failure';


            var state = '';
            var description = '';
            var context_name = "Octopus Clients PR Comment Check";

            if (validateCommentsFailed) {
              state = 'failure';

              var errors = [];

              const releaseNotesFailedMessage = '${{ steps.get_and_validate_comments.outputs.release_notes_error }}';
              if (releaseNotesFailedMessage) {
                errors.push(releaseNotesFailedMessage);
              }
              const semverFailedMessage = '${{ steps.get_and_validate_comments.outputs.semver_error }}';
              if (semverFailedMessage) {
                errors.push(semverFailedMessage);
              }
              description = errors.join(', ');

            } else {
              state = 'success';
              description = 'All required comments are present and valid';
            }

            // Set the commit status to reflect the success or failure of the previous steps.
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state,
              context: context_name,
              description: description,
            });