name: Octopus Clients PR Comment Check

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      # This is bypassed by the clients-pr-comment-bypass.yaml workflow. It will automatically set a success status for non-clients PRs.
      - 'clients/**' 

jobs:
  validate-pr-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        id: get_and_validate_pr_description
        uses: actions/github-script@v7
        with:
          script: |
            const prDescription = context.payload.pull_request.body || '';
            console.log('PR Description:', prDescription);

            // ----------------------------
            // Get & Validate "release notes:"
            // ----------------------------

            // Check if the PR description contains "release notes:"
            const releaseNotesMatch = prDescription.toLowerCase().match(/release notes:\s*([\s\S]*?)(?=\n\s*semver:|$)/);
            
            if (!releaseNotesMatch) {
              core.setFailed('"release notes:" section is missing from PR description');
              core.setOutput('release_notes_error', '"release notes:" section is missing from PR description');
            } else {
              // Validate the content of the release notes
              const releaseNotesContent = releaseNotesMatch[1]?.trim();
              if (!releaseNotesContent || releaseNotesContent.length === 0) {
                core.setFailed('"release notes:" section found but no content');
                core.setOutput('release_notes_error', '"release notes:" section found but no content');
              }
            }

            // ----------------------------
            // Get & Validate "semver:"
            // ----------------------------

            const allowedSemverValues = ["breaking", "feature", "no breaking changes", "major", "minor", "patch"];

            // Check if the PR description contains "semver:"
            const semverMatch = prDescription.toLowerCase().match(/semver:\s*(.+)/);
            
            if (!semverMatch) {
              core.setOutput('semver_error', '"semver:" section is missing from PR description');
              core.setFailed('"semver:" section is missing from PR description');
            } else {  
              // Validate the content of the semver
              const semverValue = semverMatch[1].trim();
              console.log(`Semver value found: "${semverValue}"`);
              console.log(`Allowed values: ${allowedSemverValues.join(', ')}`);

              if (!semverValue || !allowedSemverValues.includes(semverValue)) {
                core.setOutput('semver_error', `"semver:" section found but invalid value: "${semverValue}". Allowed: ${allowedSemverValues.join(', ')}`);
                core.setFailed(`"semver:" section found but invalid value: "${semverValue}". Allowed: ${allowedSemverValues.join(', ')}`);
              }
            }

      - name: Set success status
        id: set_success_status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            // using the potential `core.setFailed` of the previous steps update the create commit status to reflect success or failure from previous steps. combining the failed failures
            const validateDescriptionFailed = '${{ steps.get_and_validate_pr_description.outcome }}' === 'failure';

            var state = '';
            var description = '';
            var context_name = "Octopus Clients PR Comment Check";

            if (validateDescriptionFailed) {
              state = 'failure';

              var errors = [];

              const releaseNotesFailedMessage = '${{ steps.get_and_validate_pr_description.outputs.release_notes_error }}';
              if (releaseNotesFailedMessage) {
                errors.push(releaseNotesFailedMessage);
              }
              const semverFailedMessage = '${{ steps.get_and_validate_pr_description.outputs.semver_error }}';
              if (semverFailedMessage) {
                errors.push(semverFailedMessage);
              }
              description = errors.join(', ');

            } else {
              state = 'success';
              description = 'All required sections are present and valid in PR description';
            }

            // Set the commit status to reflect the success or failure of the previous steps.
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state,
              context: context_name,
              description: description,
            });